apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - name: external
      port: {{ .Values.kafka.ports.external }}
      targetPort: {{ .Values.kafka.ports.external }}
    - name: internal
      port: {{ .Values.kafka.ports.internal }}
      targetPort: {{ .Values.kafka.ports.internal }}
  selector:
    app: kafka
