apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: hari-practiced
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: {{ .Values.kafkaUi.image }}
          ports:
            - containerPort: {{ .Values.kafkaUi.port }}
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: local
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka:{{ .Values.kafka.brokerPort }}
            - name: KAFKA_CLUSTERS_0_ZOOKEEPER
              value: zookeeper:{{ .Values.zookeeper.clientPort }}
