apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: elk-stack
data:
  logstash.conf: |
    input {
      tcp {
        port => 5000
        codec => json_lines
      }
    }

    filter {
      if [app] {
        mutate {
          add_field => { "index_name" => "%{app}-logs" }
        }
      } else {
        mutate {
          add_field => { "index_name" => "unknown-logs" }
        }
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "%{index_name}-%{+YYYY.MM.dd}"
      }

      stdout { codec => rubydebug }
    }