apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  namespace: redis
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
  selector:
    app: {{ include "redis.name" . }}