apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.snowflake.passwordSecretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  password: {{ .Values.snowflake.password | quote }}