apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
  namespace: hari-practiced
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.kafka.storagePath }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
  namespace: hari-practiced
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.kafka.storageSize }}
