apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: hari-practiced
spec:
  selector:
    app: kafka
  ports:
    - port: {{ .Values.kafka.brokerPort }}
      targetPort: {{ .Values.kafka.brokerPort }}
      nodePort: {{ .Values.kafka.nodePort }}
  type: NodePort
