apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv
  namespace: hari-practiced
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.zookeeper.storagePath }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pvc
  namespace: hari-practiced
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.zookeeper.storageSize }}
