apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: hari-practiced
spec:
  selector:
    app: zookeeper
  ports:
    - port: {{ .Values.zookeeper.clientPort }}
      targetPort: {{ .Values.zookeeper.clientPort }}
      nodePort: {{ .Values.zookeeper.nodePort }}
  type: NodePort
