zookeeper:
  image: confluentinc/cp-zookeeper:7.6.0
  port: 2181

kafka:
  image: confluentinc/cp-kafka:7.6.0
  ports:
    external: 9092
    internal: 29092

kafdrop:
  image: obsidiandynamics/kafdrop:latest
  port: 9000