apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-pvc
  namespace: hari-practiced
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.oracle.storageSize }}